// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vgimfqorqplhmfpggqkc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZnaW1mcW9ycXBsaG1mcGdncWtjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTIxODAsImV4cCI6MjA2NTQ2ODE4MH0.ndO7luWH9QXaCnXMBMHrsJ1tjWIJkW4o85XpPLF0e5g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);